# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    resolvers:
        default:
            web_path: ~
    
    filter_sets:
        cache: ~

        miniaturesdiapo:
            quality: 80
            filters:
                scale:
                    dim: [ 250, 250 ]

        min150:
            quality: 70
            filters:
                relative_resize: 
                    widen: 150 # Shrink/upscale the image to 800px of height, with full quality 

        min300:
            quality: 70
            filters:
                relative_resize: 
                    widen: 300 # Shrink/upscale the image to 800px of height, with full quality 